version: "3.0"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./sql/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
    ports:
      - "33060:3306"
  mueblesstgo:
    container_name: mueblesstgo
    image: ibanezbendezu/mueblesstgo
    ports:
      - "8090:8090"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=pass
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
volumes:
  mysql-data: