drop schema if exists DB;
create schema if not exists DB;
create table DB.CATEGORY (
                          ID int generated by default as identity not null,
                          TYPE char not null,
                          FIXED_MONTHLY_WAGE int not null,
                          primary key (ID)
);
create table DB.EMPLOYEE (
                          ID int generated by default as identity not null,
                          RUT varchar(30) not null,
                          LAST_NAMES varchar(30) not null,
                          FIRST_NAMES varchar(30) not null,
                          BIRTH_DATE date not null,
                          HIRE_DATE date not null,
                          CATEGORY_ID int not null,
                          primary key (ID),
                          foreign key (CATEGORY_ID)
                              references DB.CATEGORY (ID)
);
create table DB.OVERTIME_APPROVAL (
                                   ID int generated by default as identity not null,
                                   APPROVAL_DATE date not null,
                                   DETAILS varchar(200),
                                   EMPLOYEE_ID int not null,
                                   primary key (ID),
                                   foreign key (EMPLOYEE_ID)
                                       references DB.EMPLOYEE (ID)
);
create table DB.ABSENCE_JUSTIFICATION (
                                       ID int generated by default as identity not null,
                                       JUSTIFICATION_DATE date not null,
                                       DETAILS varchar(200),
                                       STATUS boolean,
                                       EMPLOYEE_ID int not null,
                                       primary key (ID),
                                       foreign key (EMPLOYEE_ID)
                                           references DB.EMPLOYEE (ID)
);
create table DB.WORKED_DAY (
                            ID int generated by default as identity not null,
                            DATE date,
                            CLOCK_IN time,
                            CLOCK_OUT time,
                            OVERTIME double precision,
                            MINUTES_LATE int,
                            EMPLOYEE_ID int not null,
                            primary key (ID),
                            foreign key (EMPLOYEE_ID)
                                references DB.EMPLOYEE (ID)
);
create table DB.WAGE (
                      ID int generated by default as identity not null,
                      DATE date not null,
                      EMPLOYEE_ID int not null,
                      primary key (ID),
                      foreign key (EMPLOYEE_ID)
                          references DB.EMPLOYEE (ID)
);
create table DB.WAGE_DETAIL (
                             ID int generated by default as identity not null,
                             NAME varchar(30) not null,
                             TYPE varchar(30) not null,
                             AMOUNT bigint not null,
                             WAGE_ID int not null,
                             primary key (ID),
                             foreign key (WAGE_ID)
                                 references DB.WAGE (ID)
);
create table DB.WORKING_DAYS (
                              ID int generated by default as identity not null,
                              YEAR int not null,
                              MONTH int not null,
                              AMOUNT int not null,
                              primary key (ID)
);
insert into DB.WORKING_DAYS (YEAR, MONTH, AMOUNT)
values (
           2022,
           1,
           21
       ), (
           2022,
           2,
           20
       ), (
           2022,
           3,
           23
       ), (
           2022,
           4,
           20
       ), (
           2022,
           5,
           22
       ), (
           2022,
           6,
           22
       ), (
           2022,
           7,
           21
       ), (
           2022,
           8,
           22
       ), (
           2022,
           9,
           21
       ), (
           2022,
           10,
           19
       ), (
           2022,
           11,
           21
       ), (
           2022,
           12,
           21
       );
insert into DB.CATEGORY (TYPE, FIXED_MONTHLY_WAGE)
values (
           'A',
           1700000
       ), (
           'B',
           1200000
       ), (
           'C',
           800000
       );
insert into DB.EMPLOYEE (
    RUT,
    LAST_NAMES,
    FIRST_NAMES,
    BIRTH_DATE,
    HIRE_DATE,
    CATEGORY_ID
)
values (
           '14.707.441-7',
           'Ibanez Bendezu',
           'Aaron Andre',
           '1996-01-29',
           '2022-09-06',
           (
               select ID
               from DB.CATEGORY
               where TYPE = 'A'
           )
       ), (
           '6.591.049-7',
           'Gonzalez Reyes',
           'Boris Leonardo',
           '1952-11-03',
           '1987-04-22',
           (
               select ID
               from DB.CATEGORY
               where TYPE = 'C'
           )
       );
insert into DB.OVERTIME_APPROVAL (APPROVAL_DATE, DETAILS, EMPLOYEE_ID)
values (
           '2022-09-17',
           'approval',
           1
       );
insert into DB.ABSENCE_JUSTIFICATION (JUSTIFICATION_DATE, DETAILS, STATUS, EMPLOYEE_ID)
values (
           '2022-09-05',
           'justification',
           true,
           2
       );